name: step_up_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^1.1.6
  go_router: ^14.3.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  injectable_generator: ^2.1.3
  pretty_dio_logger: ^1.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  retrofit: ^4.5.0
  intl: ^0.20.2
  fluttertoast: ^8.2.8
  flutter_timezone: ^3.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svg/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
